### ISSUE TITLE
mbedtls 对接硬件加密模块效率问题

### ISSUE THREAD

**Issue by Sliverguo** [RT-Thread/packages#1043]
如下图所示，目前我们加密函数每次加密的长度为16个字节，但是有些硬件模块一次处理的数据长度可能远远大于16个字节，将数据强制按照16个字节处理的话，会大大影响加密的效率，是否有更好的处理方案？

![image](https://user-images.githubusercontent.com/23095389/134625488-b9857bc7-80a5-4859-8928-94e2b1bf9d56.png)

**Comment by mysterywolf** [comment]
https://club.rt-thread.org/index.html 请到论坛寻求帮助，issue一般是用来反馈bug用的。

**Comment by mysterywolf** [comment]
如果你认为此处设计不合理，请到上游mbedtls官方仓库的issue采用英文进行反馈 https://github.com/ARMmbed/mbedtls
