### ISSUE TITLE
能否支持 代码和 索引信息都在一个版本库里面

### ISSUE THREAD

**Issue by maikebing** [RT-Thread/packages#1324]
如果 我要建 私有 packages 库， 我想把索引信息和代码都在 一个库里， 而不是像现在官方这样索引是总库， 代码是git仓库或者zip。

**Comment by mysterywolf** [comment]
欢迎提交PR

**Comment by maikebing** [comment]
那我待学一下python。 这是个漫长的过程。

**Comment by sgf** [comment]
> 那我待学一下python。 这是个漫长的过程。

有这个鸟时间要不然自己改造一下 C#的操作系统作为IOT的操作系统？ 可惜我对操作系统没啥研究。C#有几个操作系统界面化了，虽然比较简陋。

**Comment by mysterywolf** [comment]
C#怎么运行在微控制器上？

**Comment by maikebing** [comment]
nanoframework  可以。  
https://github.com/nanoframework
