### ISSUE TITLE
Could not find reverse dependency symbol. Name = PKG_EASYFLASH_ENABLE_LOG.

### ISSUE THREAD

**Issue by ArdaFu** [RT-Thread/packages#138]
Could not find reverse dependency symbol. Name = PKG_EASYFLASH_ENABLE_LOG. In file ".\packages\tools\EasyLogger\Kconfig", at line 92.
The define in file ".\packages\tools\EasyFlash\Kconfig", at line 55 is PKG_EASYFLASH_LOG 
@armink

**Comment by armink** [comment]
Thx, it's fixed.
