### ISSUE TITLE
kernel sample

### ISSUE THREAD

**Issue by messigogogo** [RT-Thread/packages#1629]
![e9aaac079bda2a9531e91eee37cbe9f](https://github.com/RT-Thread/packages/assets/103986797/faa82d2c-d65e-49ab-a054-ab4323a3507c)
rt_thread里已经没有name变量了，这里需要更新

**Comment by mysterywolf** [comment]
@Z8MAN8 仕成 麻烦看看这个issue

**Comment by Z8MAN8** [comment]
> @Z8MAN8 仕成 麻烦看看这个issue
好的，我会尽快修复

**Comment by Z8MAN8** [comment]
> @Z8MAN8 仕成 麻烦看看这个issue

好的，我会尽快修复

**Comment by Z8MAN8** [comment]
@mysterywolf  https://github.com/RT-Thread-packages/kernel-sample/pull/26
