### ISSUE TITLE
Kconfig:9: unknown option "rsource"

### ISSUE THREAD

**Issue by cltsp** [RT-Thread/packages#1742]
❯ scons --menuconfig
scons: Reading SConscript files ...
scons: Entering directory `/Users/charlie/rt-thread-5.0.2/tools/kconfig-frontends'
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
scons: `.' is up to date.
scons: done building targets.
Cloning into '/Users/charlie/.env/packages/packages'...
remote: Enumerating objects: 21016, done.
remote: Counting objects: 100% (2133/2133), done.
remote: Compressing objects: 100% (310/310), done.
remote: Total 21016 (delta 1869), reused 1969 (delta 1822), pack-reused 18883
Receiving objects: 100% (21016/21016), 3.59 MiB | 789.00 KiB/s, done.
Resolving deltas: 100% (11596/11596), done.
Cloning into '/Users/charlie/.env/tools/scripts'...
remote: Enumerating objects: 2199, done.
remote: Counting objects: 100% (339/339), done.
remote: Compressing objects: 100% (128/128), done.
remote: Total 2199 (delta 227), reused 261 (delta 210), pack-reused 1860
Receiving objects: 100% (2199/2199), 2.55 MiB | 1.38 MiB/s, done.
Resolving deltas: 100% (1478/1478), done.
Kconfig:3:warning: environment variable BSP_ROOT undefined
/Users/charlie/.env/packages/packages/Kconfig:4: syntax error
/Users/charlie/.env/packages/packages/Kconfig:3: unknown option "rsource"
/Users/charlie/.env/packages/packages/Kconfig:4: unknown option "rsource"
/Users/charlie/.env/packages/packages/Kconfig:5: unknown option "rsource"
/Users/charlie/.env/packages/packages/Kconfig:6: unknown option "rsource"
/Users/charlie/.env/packages/packages/Kconfig:7: unknown option "rsource"
/Users/charlie/.env/packages/packages/Kconfig:8: unknown option "rsource"
/Users/charlie/.env/packages/packages/Kconfig:9: unknown option "rsource"
/Users/charlie/.env/packages/packages/Kconfig:10: unknown option "rsource"
/Users/charlie/.env/packages/packages/Kconfig:11: unknown option "rsource"
/Users/charlie/.env/packages/packages/Kconfig:12: unknown option "rsource"
/Users/charlie/.env/packages/packages/Kconfig:13: unknown option "rsource"

**Comment by Rbb666** [comment]
请升级最新的env即可解决问题：https://github.com/RT-Thread/env
