### ISSUE TITLE
为了解决 RT-Thread nRF24L01 软件包在 STM32F103C8 上死活调不通的问题，我都干了啥？

### ISSUE THREAD

**Issue by SuWeipeng** [RT-Thread/packages#512]
> 背景介绍：      
> Sugar 的[《软件架构训练计划》](https://mp.weixin.qq.com/s/6wM1kMKWpOJxBatzTNxShQ)用的是 CubeMX 第三方软件包和 RT-Thread 混合代码，为了练习故意这么整的。       
> 在[《RT-Thread STM32 虚拟串口代码级移植》](https://mp.weixin.qq.com/s/ndyMISoiWHqHw-WBzF-CPw)一文中说过，Sugar 未来目标是带着读者回归 RT-Thread 大集体中去。
> 为了迈出回归第一步，并且带初入门者了解代码，Sugar 从自己开源的麦轮车遥控代码开使入手，第一步就先把 nRF24L01 的驱动换掉。       
> nRF24L01 的驱动在 IoT Board 上就好好的，到遥控的主控芯片 STM32F103C8 上就死活不通，于是探索就开始了。      

第一步，动脑分析与动手验证
---
> 这里主要说一下问题方法，遇事不要慌。

一、是软件问题么？     
Sugar 在 IoT Board（潘多拉开发板）上和遥控器上用了同样的官方示例代码。     
IoT Board 上没问题，遥控上初始化死活不成功。       
因为是基于 RTOS 的代码，应用层复制过去就行，SPI 驱动也已经调好，所以不存在代码内容不一样的问题（为了求证，还特意用 Beyond Compare 对比了一下，确定没改啥）。         
好的，至此确定：肯定不是软件代码复制错了。       
二、是硬件坏了么？       
同样的硬件，换上 Sugar 以前基于 CubeMX 的 C++ 代码，动手验证，能控车，硬件没问题。       

软件代码一样，硬件好使，IoT Board 就行，遥控就死活初始化不成功，揪净为啥啊（看吧，程序员又揪头发了）。

第二步，回归本源
---
> 一般遇到这种问题，首先怀疑的就是驱动软件代码还有提升空间。      
> 但揪净怎么提升呢？还是要看枯燥的 datasheet。        
> 年龄大了，看 datasheet 的耐心不足了。还好 Sugar 打小时候就沉迷书法，于是有了下面的作品。

![](https://github.com/SuWeipeng/img/raw/master/12_RT-Thread/nrf24%20(1).jpg)        
![](https://github.com/SuWeipeng/img/raw/master/12_RT-Thread/nrf24%20(2).jpg)        
![](https://github.com/SuWeipeng/img/raw/master/12_RT-Thread/nrf24%20(3).jpg)        
![](https://github.com/SuWeipeng/img/raw/master/12_RT-Thread/nrf24%20(4).jpg)        
![](https://github.com/SuWeipeng/img/raw/master/12_RT-Thread/nrf24%20(5).jpg)        
![](https://github.com/SuWeipeng/img/raw/master/12_RT-Thread/nrf24%20(6).jpg)        
![](https://github.com/SuWeipeng/img/raw/master/12_RT-Thread/nrf24%20(7).jpg)        
![](https://github.com/SuWeipeng/img/raw/master/12_RT-Thread/nrf24%20(8).jpg)        

最后，找到原因了
---
> 在上面练字过程中，有句话带来灵感，最终加了一句代码搞定了。

![](https://github.com/SuWeipeng/img/raw/master/12_RT-Thread/nrf24%20(9).jpg)        

关注作者
---
欢迎扫码关注我的公众号`MultiMCU EDU`。
![](https://github.com/SuWeipeng/img/raw/master/gongzonghao.jpg)

**Comment by balanceTWK** [comment]
我有点凌乱。。。请问你这是在打广告嘛。。。😶

**Comment by armink** [comment]
👍  这手稿堪比印刷体了

**Comment by SummerLife** [comment]
这很神奇
