### ISSUE TITLE
一些软件包体积过大了，例如 realtek_ameba 软件包达到上百兆

### ISSUE THREAD

**Issue by SummerLife** [RT-Thread/packages#528]
对于加入的软件包，除了必要的代码和说明文档外，不应该将整个 SDK 的东西都提交上来。

**Comment by SummerLife** [comment]
后续应当对提交软件包的体积做检查。

**Comment by mysterywolf** [comment]
可以在sconscrip脚本中 使用shutil库的rmtree函数 对构建工程没有用的文件下载之后进行一个删除，这样既保证了厂家sdk的完整性，也保证了用户拿到的软件包体积不会太大。我已经实践过了：https://github.com/mysterywolf/RT-Thread-wrapper-of-uCOS-III/blob/master/SConscript#L18
