### ISSUE TITLE
GPRS 模组驱动 A9G，调试遇到AT指令发送失败

### ISSUE THREAD

**Issue by useisbb** [RT-Thread/packages#537]
我的A9G 版本：V02.02.20190915R
由于AT 指令OK 和 CMD ACK 中间有多个 /0X0D ,/0X0A 也就是\r\n
实际收到的数据往往是 /0X0D ,/0X0A OK /0X0D ,/0X0A ,  /0X0D ,/0X0A ACK /0X0D ,/0X0A，
由于字符串分割后将0X0A 替换为00，本来代码的字面意思为ACK 在line 2 ，单由于中间有一样0x0d，实际ack在line3
所以判断为命令超时

代码补丁已经修改，但没有上传

**Comment by mysterywolf** [comment]
你好可否提交一个pr到此处？https://github.com/RT-Thread-packages/at_device
或者将问题转移到这个仓库的issue
