### ISSUE TITLE
kconfig书写不规范

### ISSUE THREAD

**Issue by geniusgogo** [RT-Thread/packages#649]
https://github.com/RT-Thread/packages/blob/7c8347191eda888d27efc8f60e75acc5ee6dbdd5/peripherals/lora_radio_driver/Kconfig#L46

BSP_USING_XXX的config不应该出现在这些地方，这会导致和BSP驱动目录里的配置冲突，如果只是依赖的话，应该使用类似select来进行依赖选择，而不是另起炉灶进行BSP_USING的配置，或者不要使用BSP_USING作为前缀以免和驱动目录冲突。

**Comment by Forest-Rain** [comment]
很棒的建议, BSP_USING_SPIx 后续会调整到BSP文件夹对应board的kconfig中，有利于lora-radio软件包适配更多硬件（mcu）平台 @geniusgogo

**Comment by mysterywolf** [comment]
已经确认全部移除了
