### ISSUE TITLE
packages/iot/ljson/package.json文件少了一个逗号。

### ISSUE THREAD

**Issue by teddyxiong53** [RT-Thread/packages#77]
{"version" : "v0.0.2", "URL" : "https://github.com/qiaoqidui/ljson/archive/v0.0.2.zip", "filename" : "ljson-0.0.2.zip"} 后面少了逗号，会导致pkgs --update出错。

**Comment by aozima** [comment]
@qiaoqidui 
推荐个挺方便的JSON在线编辑器 http://qqe2.com/

**Comment by BernardXiong** [comment]
谢谢提出，已经改正了。 @qiaoqidui 请多多注意类似问题，已经出过好几次这样的问题了。
